### PR TITLE
docker: remove unnecessary comma

### PR DESCRIPTION
**Pull request by gyscos**

### CODE REVIEW

**Comment by archlinux-github** [comment]
This project is a read-only mirror.

*This comment was generated by [github-pull-closer](https://gitlab.archlinux.org/archlinux/github-pull-closer).*

**Comment by Foxboron** [comment]
https://github.com/Foxboron/archlinux-pkgbuilds/tree/master/docker

:)

**Comment by gyscos** [comment]
Thanks! Wasn't sure where to look :S

**Comment by Foxboron** [comment]
It's all SVN so there isnt anywhere to look unless the maintainer is mirroring something with scripts.

**Pull request closed without merging**
